### ISSUE TITLE
Doughnut returns empty arrays

### ISSUE THREAD

**Issue by agumaxwellforcode** [sakanjo/laravel-easy-metrics#10]
Trend works,  same with Value, but Doughnut  doesn't work

  [$labels, $data] = Doughnut::make(User::class)
        ->options(UserSexEnum::class)
        ->count('sex', 'sex');

returns
[
  [],
  []
]

**Comment by sakanjo** [comment]
I fail to discover why this happens, could you provide more information about the used enum and the model ?
