### ISSUE TITLE
How do you add filtering to elequent model?

### ISSUE THREAD

**Issue by bauersfeld** [sakanjo/laravel-easy-metrics#11]
I'm trying to add simple filtering to value, but it's returning zero for count when it should be non-zero.  What am I doing wrong?

$admin_count = Value::make(User::where('is_admin', true))
								->count();

**Comment by sakanjo** [comment]
@bauersfeld That line is the way, maybe you are applying a global scope. Try bypassing it with User::withoutGlobalScopes()->where('is_admin', true)
