### ISSUE TITLE
Column not found: 1054 Unknown column 'date_result' in 'group statement'

### ISSUE THREAD

**Issue by oozman** [sakanjo/laravel-easy-metrics#4]
Having this issue when:

```php
$query = Subscriber::query()->whereRelation('link', 'user_id', $user->id);
$totalAmount = Value::make($query)->sum('cost');
```

**Comment by sakanjo** [comment]
@oozman Thanks for reporting,

I tried to reproduce the bug, and everything appears to be working correctly on my end. Could you please provide more information?

**Comment by oozman** [comment]
This is working... Just figured out when `query` is passed as parameter, somewhere down the line it's modified. And when `query` is reused again or passed again as parameter, this error happens. I think there's something in `whereRelation()`. Or it's passing `query` as reference.

My work around is by using `clone`:

```php
Value::make(clone query)->sum('cost')
```

**Comment by sakanjo** [comment]
@oozman thanks for the clarification, in the next release you can delete the clone as i am gonna add it.
